services:
  userservice:
    build:
      context: .
      dockerfile: build/docker/userservice.dockerfile
    ports:
      - "50051:50051"
    networks:
      - app-networks

  chatservice:
    build:
      context: .
      dockerfile: build/docker/chatservice.dockerfile
    ports:
      - "50052:50052"
    networks:
      - app-networks

  gateway:
    build:
      context: .
      dockerfile: build/docker/gateway.dockerfile
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_ADDR: userservice:50051
      CHAT_SERVICE_ADDR: chatservice:50052
    depends_on:
      - userservice
      - chatservice
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge