// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type UserProfile interface {
	IsUserProfile()
}

type AnswerMessageInput struct {
	Content    string `json:"content"`
	QuestionID string `json:"questionId"`
}

type CreateUserInput struct {
	Name         string                    `json:"name"`
	Email        string                    `json:"email"`
	Description  *string                   `json:"description,omitempty"`
	Professional *ProfessionalProfileInput `json:"professional,omitempty"`
	General      *GeneralProfileInput      `json:"general,omitempty"`
}

type GeneralProfile struct {
	Points       int32  `json:"points"`
	Introduction string `json:"introduction"`
}

func (GeneralProfile) IsUserProfile() {}

type GeneralProfileInput struct {
	Points       int32  `json:"points"`
	Introduction string `json:"introduction"`
}

type Message struct {
	ID       string    `json:"id"`
	ChatID   string    `json:"chatId"`
	SenderID string    `json:"senderId"`
	SentAt   time.Time `json:"sentAt"`
}

type Mutation struct {
}

type ProfessionalProfile struct {
	ProBadgeURL string `json:"proBadgeUrl"`
	Biography   string `json:"biography"`
}

func (ProfessionalProfile) IsUserProfile() {}

type ProfessionalProfileInput struct {
	ProBadgeURL string `json:"proBadgeUrl"`
	Biography   string `json:"biography"`
}

type PromotionalMessageInput struct {
	Title     string  `json:"title"`
	Body      string  `json:"body"`
	ActionURL string  `json:"actionUrl"`
	ImageURL  *string `json:"imageUrl,omitempty"`
}

type Query struct {
}

type QuestionMessageInput struct {
	Content string   `json:"content"`
	Tags    []string `json:"tags,omitempty"`
}

type SendMessageInput struct {
	ChatID      string                   `json:"chatId"`
	SenderID    string                   `json:"senderId"`
	Standard    *StandardMessageInput    `json:"standard,omitempty"`
	Question    *QuestionMessageInput    `json:"question,omitempty"`
	Answer      *AnswerMessageInput      `json:"answer,omitempty"`
	Promotional *PromotionalMessageInput `json:"promotional,omitempty"`
}

type StandardMessageInput struct {
	Content string `json:"content"`
}

type User struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
	Profile   UserProfile `json:"profile,omitempty"`
}
